### ISSUE TITLE
feat: please build a multi-arch image?

### ISSUE THREAD

**Issue by diranged** [argoproj-labs/argocd-extension-installer#4]
The old argocd extensions image was multiarch - and we discovered today that this updated process is only an amd64 image. Please make this a multi-arch build so we don't have to pin our ArgoCD Server pods to AMD64 hosts.

**Comment by ajax-bychenok-y** [comment]
Old method is deprecated but new one extension image is amd64 only.

**Comment by leoluz** [comment]
Starting with tag v0.0.4 we now support multi platforms.
See: https://quay.io/repository/argoprojlabs/argocd-extension-installer?tab=tags
